In [1]:
import pandas as pd

In [2]:
# Main types:
series = pd.Series(["BMW","TOYOTA","HONDA"])
series

0       BMW
1    TOYOTA
2     HONDA
dtype: object

In [3]:
# Series= 1-Dimensional
colours = pd.Series(["Red","Blue","White"])
colours

0      Red
1     Blue
2    White
dtype: object

In [4]:
# Dataframe = two-dimensional,

car_data = pd.DataFrame({"car make": series, "Colour": colours})
car_data

  car make Colour
0      BMW    Red
1   TOYOTA   Blue
2    HONDA  White

In [13]:
# Import Data
car_sales = pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00