If you’re learning Python and would like to develop a machine learning model then a library that you want to seriously consider is scikit-learn. Scikit-learn (also known as sklearn) is a machine learning library used in Python that provides many unsupervised and supervised learning algorithms.

In this simple guide, we’re going to create a machine learning model that will predict whether a movie review is positive or negative. This is known as binary text classification and will help us explore the scikit-learn library while building a basic machine learning model from scratch. These are the topics we’re going to learn in this guide.

Read full blog : https://towardsdatascience.com/a-beginners-guide-to-text-classification-with-scikit-learn-632357e16f3a

User Guide : https://scikit-learn.org/stable/user_guide.html

# What we are going to cover:

* An end-to-end Scikit-Learn workflow
* Getting data ready ( to be used with machine learning models)
* Choosing a machine learning model
* Fitting a model to the data (learning patterns)
* Making Predictions with a model (using patterns)
* Evaluating model predictions
* Improving model predictions
* Saving and loading models

# An end-to-end Scikit-Learn workflow

In [1]:
# Import data
import pandas as pd
import numpy as np
heart_disease = pd.read_csv('heart-disease.csv')

In [2]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [3]:
# Create x (features matrix)
X = heart_disease.drop("target", axis =1)

# Create y
y = heart_disease["target"]

In [4]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators= 100)

# We will keep the defailt hyper-parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state= 42)

In [6]:
# All models/estimators have the fit() function built-in
clf.fit(X_train, y_train)

# Once fit is called, you can make predictions using predict()
y_preds = clf.predict(X_test)

# You can also predict with probabilities (on classification models)
y_probs = clf.predict_proba(X_test)

# View preds/probabilities
y_preds, y_probs

(array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([[0.91, 0.09],
        [0.37, 0.63],
        [0.52, 0.48],
        [0.89, 0.11],
        [0.27, 0.73],
        [0.14, 0.86],
        [0.4 , 0.6 ],
        [0.98, 0.02],
        [0.93, 0.07],
        [0.45, 0.55],
        [0.26, 0.74],
        [0.78, 0.22],
        [0.1 , 0.9 ],
        [0.89, 0.11],
        [0.01, 0.99],
        [0.01, 0.99],
        [0.  , 1.  ],
        [0.91, 0.09],
        [0.94, 0.06],
        [0.9 , 0.1 ],
        [0.5 , 0.5 ],
        [0.89, 0.11],
        [0.31, 0.69],
        [0.21, 0.79],
        [0.33, 0.67],
        [0.31, 0.69],
        [0.24, 0.76],
        [0.22, 0.78],
        [0.92, 0.08],
        [0.21, 0.79],
        [0.93, 0.07],
        [0.91, 0.09],
        [0.98, 0.02],
        [0.7 , 0.3 ],
        [0.46, 0.54],
        [0.83, 0.17],
        [0.4 , 0.6 ],
        [0.18, 0.82],
        [0.4 , 0.6 ],
        [0.15, 0.85],
        [0.18, 0.82],
        [0.23, 0.77],
        [0.15, 0.85],
        [0.28, 0.72],
        [0.33, 0.67],
        [0.77, 0.23],
        [0.45, 0.55],
        [0.01, 0.99],
        [0.86, 0.14],
        [0.98, 0.02],
        [0.81, 0.19],
        [0.8 , 0.2 ],
        [0.24, 0.76],
        [0.27, 0.73],
        [0.84, 0.16],
        [0.86, 0.14],
        [0.6 , 0.4 ],
        [0.01, 0.99],
        [0.91, 0.09],
        [1.  , 0.  ],
        [0.89, 0.11]]))

In [7]:
# 4. Evaluate the model

In [8]:
clf.score(X_test, y_test)

0.8360655737704918

In [9]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train)

1.0

In [10]:
# Evaluting a model using cross-validation is possible with cross_val_score
from sklearn.model_selection import cross_val_score

# scoring=None means default score() metric is used
print(cross_val_score(estimator=clf, 
                      X=X, 
                      y=y, 
                      cv=5, # use 5-fold cross-validation
                      scoring=None)) 

# Evaluate a model with a different scoring method
print(cross_val_score(estimator=clf, 
                      X=X, 
                      y=y,
                      cv=5, # use 5-fold cross-validation
                      scoring="precision"))

[0.81967213 0.8852459  0.78688525 0.78333333 0.75      ]
[0.82857143 0.93548387 0.85294118 0.82857143 0.73684211]

In [11]:
# Different classification metrics

# Accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_preds))

# Reciver Operating Characteristic (ROC curve)/Area under curve (AUC)
from sklearn.metrics import roc_curve, roc_auc_score
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_probs[:, 1])
print(roc_auc_score(y_test, y_preds))

# Confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_preds))

# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_preds))

0.8360655737704918
0.8356681034482758
[[24  5]
 [ 5 27]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

# Getting the data Ready:

In [13]:
# import libs 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:
# 1. Getting out data ready to be used with machine learning

Three main things we have to do:
1. Split the data inro features and labels (usually `X` & `y`)
2. Filling (also called imputing) or disregarding missing values
3. Converting non-numerical values to numerical values (also called feature encoding)

In [20]:
# Creae x and y data 
x = heart_disease.drop(("target"),axis = 1 )
y = heart_disease["target"]

In [23]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [24]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [25]:
# Split the data into training and test sets:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size= 0.2 , random_state= 42)

In [26]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [27]:
X.shape

(303, 13)

In [28]:
len(heart_disease)

303

# # 1.1 Make sure it's all numerical

In [34]:
car_sales = pd.read_csv('car-sales-extended.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [35]:
len(car_sales)

1000

In [36]:
# Split the data in x and y

In [39]:
# Split inro x and y
X = car_sales.drop("Price", axis = 1)
y = car_sales["Price"]

In [40]:
# Split data into train test 
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2)

In [41]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Honda'

`ValueError:` could not convert string to float: 'Honda'

In [42]:
# We have to convert strings into numbers:

In [44]:
from sklearn.preprocessing import  OneHotEncoder
from sklearn.compose import ColumnTransformer

In [48]:
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder= "passthrough")

transformed_x = transformer.fit_transform(X)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [50]:
pd.DataFrame(transformed_x) # we took one hot encoder and applied on categorical feature

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]